# btipay/config/front/services.yml
imports:
  - { resource: ../common.yml }

services:
  btipay.validator.availability:
    class: BTiPay\Validator\Availability\AvailabilityValidatorPool
    public: true
    arguments:
      - '@btipay.config'
      - [
        'BTiPay\Validator\Availability\GeneralValidator',
        'BTiPay\Validator\Availability\CountryValidator',
        'BTiPay\Validator\Availability\CurrencyValidator'
      ]

  btipay.authorize.command:
    class: BTiPay\Command\ActionCommand
    public: true
    arguments:
      - 'authorize'
      - '@btipay.order.request'
      - '@BTiPay\Client\BtpayClient'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.common.response.validator'
      - '@btipay.order.response.handler'

  btipay.order.command:
    class: BTiPay\Command\ActionCommand
    public: true
    arguments:
      - 'order'
      - '@btipay.order.request'
      - '@BTiPay\Client\BtpayClient'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.common.response.validator'
      - '@btipay.order.response.handler'

  btipay.order.request:
    class: BTiPay\Request\BuilderComposite
    public: true
    arguments:
      - '@btipay.pst_map_factory'
      - [
        'BTiPay\Request\OrderRequestBuilder',
        'BTiPay\Request\OrderBundleRequestBuilder',
        'BTiPay\Request\CustomerRequestBuilder',
        '@btipay.save_card.request',
        'BTiPay\Request\AdditionalParametersBuilder'
      ]

  btipay.request.builder.composite:
    class: BTiPay\Request\BuilderComposite
    public: true
    arguments:
      - '@btipay.pst_map_factory'

  btipay.save_card.request:
    class: BTiPay\Request\SaveCardsRequestBuilder
    public: true
    arguments: [ '@btipay.card_repository' ]

  btipay.order.response.handler:
    class: BTiPay\Response\HandlerChain
    public: true
    arguments:
      - '@btipay.pst_map_factory'
      - [
        '@btipay.save_transaction_handler',
      ]

  btipay.save_transaction_handler:
    class: BTiPay\Response\SaveTransactionHandler
    public: true
    arguments: [ '@btipay.payment_repository' ]