services:
  _defaults:
    public: true

  btipay.facade.context:
    class: BTiPay\Facade\Context

  btipay.facade.configuration:
    class: BTiPay\Facade\Configuration
    arguments: [ '@btipay.facade.context' ]

  btipay.config:
    class: BTiPay\Config\BTiPayConfig
    arguments: [ '@btipay.facade.configuration' ]

  btipay.logger:
    class: Monolog\Logger
    public: true
    factory: ['BTiPay\Logger\LoggerFactory', 'createLogger']
    arguments: ['btipay']

  btipay.order_state_installer:
    class: BTiPay\Helper\OrderStateInstaller
    arguments:
     - '@btipay.facade.configuration'

  btipay.pst_map_factory:
    class: BTiPay\Factory\PSTMapFactory
    public: true

# Repository
  btipay.payment_repository:
    class: BTiPay\Repository\PaymentRepository
    public: true

  btipay.card_repository:
    class: BTiPay\Repository\CardRepository
    public: true

  btipay.refund_repository:
    class: BTiPay\Repository\RefundRepository
    public: true

# Commands
  BTiPay\Client\BtpayClient:
    class: BTiPay\Client\BtpayClient
    public: true
    arguments:
      - '@btipay.config'
      - '@btipay.facade.context'
      - '@btipay.logger'

  btipay.common.response.validator:
    class: BTiPay\Validator\ValidatorPool
    public: true
    arguments:
      - '@btipay.config'
      - [ 'BTiPay\Validator\Response\StatusValidator' ]

  btipay.payment_details.service:
    class: BTiPay\Service\PaymentDetailsService
    public: true
    arguments:
      - '@BTiPay\Client\BtpayClient'

  btipay.payment_details.command:
    class: BTiPay\Command\ActionCommand
    public: true
    arguments:
      - 'getPaymentDetails'
      - '@btipay.common.request'
      - '@BTiPay\Client\BtpayClient'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.common.response.validator'
      - '@btipay.payment_details.handler'

  btipay.common.request:
    class: BTiPay\Request\BuilderComposite
    public: true
    arguments:
      - '@btipay.pst_map_factory'
      - [ 'BTiPay\Request\IPayIdRequestBuilder' ]

  btipay.payment_details.handler:
    class: BTiPay\Response\HandlerChain
    public: true
    arguments:
      - '@btipay.pst_map_factory'
      - [
        '@btipay.save_transaction_payment_details.handler',
        '@btipay.update_order_payment.handler',
        '@btipay.save_card.handler',
        '@btipay.update_order_status.handler']


  btipay.save_transaction_payment_details.handler:
    class: BTiPay\Response\SavePaymentDetailsHandler
    public: true
    arguments:
      - '@btipay.payment_repository'
      - '@btipay.payment_details.service'

  btipay.update_order_status.handler:
    class: BTiPay\Response\UpdateStatusHandler
    public: true
    arguments:
     - '@btipay.payment_repository'
     - '@btipay.config'

  btipay.save_card.handler:
    class: BTiPay\Response\SaveCardHandler
    public: true
    arguments: [ '@btipay.card_repository' ]

  btipay.update_order_payment.handler:
    class: BTiPay\Response\UpdateOrderPaymentHandler
    public: true
    arguments:
      - '@btipay.payment_details.service'

  btipay.refund.service:
    class: BTiPay\Service\RefundService
    public: true
    arguments:
      - '@btipay.config'
      - '@btipay.payment_repository'
      - '@btipay.refund_repository'
      - '@btipay.payment_details.service'
      - '@btipay.refund.command'
      - '@btipay.logger'

  btipay.refund.command:
    class: BTiPay\Command\ActionCommand
    public: true
    arguments:
      - 'refund'
      - '@btipay.refund.request'
      - '@BTiPay\Client\BtpayClient'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.common.response.validator'
      - '@btipay.refund.response.handler'

  btipay.refund.request:
    class: BTiPay\Request\BuilderComposite
    public: true
    arguments:
      - '@btipay.pst_map_factory'
      - [
        'BTiPay\Request\IPayIdRequestBuilder',
        'BTiPay\Request\AmountRequestBuilder']

  btipay.refund.response.handler:
    class: BTiPay\Response\HandlerChain
    public: true
    arguments:
      - '@btipay.pst_map_factory'
      - [ 'BTiPay\Response\RefundPaymentHandler' ]

  btipay.cancel.service:
    class: BTiPay\Service\CancelService
    public: true
    arguments:
      - '@btipay.config'
      - '@btipay.payment_repository'
      - '@btipay.payment_details.service'
      - '@btipay.cancel.command'
      - '@btipay.logger'

  btipay.cancel.command:
    class: BTiPay\Command\ActionCommand
    public: true
    arguments:
      - 'cancel'
      - '@btipay.refund.request'
      - '@BTiPay\Client\BtpayClient'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.common.response.validator'
      - '@btipay.refund.response.handler'

  btipay.capture.service:
    class: BTiPay\Service\CaptureService
    public: true
    arguments:
      - '@btipay.config'
      - '@btipay.payment_repository'
      - '@btipay.payment_details.service'
      - '@btipay.capture.command'
      - '@btipay.logger'

  btipay.capture.command:
    class: BTiPay\Command\ActionCommand
    public: true
    arguments:
      - 'capture'
      - '@btipay.refund.request'
      - '@BTiPay\Client\BtpayClient'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.common.response.validator'
      - '@btipay.refund.response.handler'

  btipay.card.service:
    class: BTiPay\Service\CardService
    public: true
    arguments:
      - '@BTiPay\Client\BtpayClient'

  btipay.jwt.service:
    class: BTiPay\Webhook\BTPayJwt
    public: true

  btipay.webhook.service:
    class: BTiPay\Webhook\WebhookService
    public: true
    arguments:
      - '@btipay.jwt.service'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.payment_repository'
      - '@btipay.refund_repository'
      - '@btipay.payment_details.service'
      - '@btipay.order.service'

  btipay.order.service:
    class: BTiPay\Service\OrderService
    public: true
    arguments:
      - '@btipay.payment_repository'
      - '@btipay.logger'